const MAIN_MENU_PATH: String = "res://scenes/main_menu/main_menu.tscn"
const POINTS_POPUP_PATH: String = "res://scenes/points_popup/points_popup.tscn"
const LOADING_SCREEN_PATH: String = "res://scenes/loading_screen/loading_screen.tscn"
const LEVEL1_PATH: String = "res://scenes/level1/level1.tscn"
const BALL_PATH: String = "res://scenes/ball/ball.tscn"
