extends Node

const MAIN_MENU_PATH: String = "res://scenes/ui/main_menu/main_menu.tscn"
const OPTIONS_MENU_PATH: String = "res://scenes/ui/options_menu/options_menu.tscn"
const POINTS_POPUP_PATH: String = "res://scenes/points_popup/points_popup.tscn"
const LOADING_SCREEN_PATH: String = "res://scenes/ui/loading_screen/loading_screen.tscn"
#const LEVEL_SELECT_MAP: String = "res://scenes/ui/level_picker/level_select_map.tscn"
const LEVEL_SELECT_MAP: String = "res://scenes/level_chooser_2.scn"
const LEVEL1_PATH: String = "res://scenes/levels/level1/level1.tscn"
const LEVEL2_PATH: String = "res://scenes/levels/level2/level2.tscn"
const LEVEL3_PATH: String = "res://scenes/levels/level3/level3.tscn"
const LEVEL4_PATH: String = "res://scenes/levels/level4/level4.tscn"
const LEVEL5_PATH: String = "res://scenes/levels/level5/level5.tscn"
const LEVEL6_PATH: String = "res://scenes/levels/level6/level6.tscn"
const LEVEL7_PATH: String = "res://scenes/levels/level7/level7.tscn"
const BALL_PATH: String = "res://scenes/ball/ball.tscn"
const PLAYER_BALL_PATH: String = "res://scenes/player_ball/player_ball.tscn"
const STAR_PARTICLE_PATH: String = "res://scenes/star_particles.tscn"
const STAR_PARTICLE2_PATH: String = "res://scenes/star_particles_2.tscn"
const STAR_PARTICLE3_PATH: String = "res://scenes/star_particles_3.tscn"
const ICE_CUBE_PATH: String = "res://scenes/balls/ice_cube.tscn"
const DECK_CHOOSE: String = "res://scenes/DeckChoose/DeckChoose.tscn"
const DECK_CHOOSE_2: String = "res://scenes/deck_chooser_2/deck_chooser.tscn"
